/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mernst_ariadna_agent_Agent */

#ifndef _Included_org_mernst_ariadna_agent_Agent
#define _Included_org_mernst_ariadna_agent_Agent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mernst_ariadna_agent_Agent
 * Method:    dump
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mernst_ariadna_agent_Agent_dump
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
